### ISSUE TITLE
Implement .NET RFC 0005

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/dotnet-core-aspnet-runtime#1]
## Describe the Enhancement

[.NET Core RFC 0005](https://github.com/paketo-buildpacks/rfcs/blob/ccfbcb20e4643d9883998ae47ae7a37c92aa3f90/text/dotnet-core/0005-simplify-runtime-dependency.md) has been approved and merged.

## Possible Solution

Create a buildpack that meets the following criteria:
- [x] Metadata
  - [x] `name` should be Paketo Buildpack for ASP.NET Core Runtime, per [RFC 0050](https://github.com/paketo-buildpacks/rfcs/blob/7a44e4e335b776917bbf1ce8d23c3baed14a0b50/text/0050-buildpack-rename.md)
  - [x] `homepage` links back to the buildpack repo
  - [x] `license` has the correct license information
  - [x] Dependency URIs are Microsoft download URIs, NOT URIs from the Paketo dep server
- [x] Detection
  - [x] `provide``dotnet-core-aspnet-runtime`
  - [x] By default, `require` nothing
  - [x] If `$BP_DOTNET_FRAMEWORK_VERSION` is set at build time, `require` `dotnet-core-aspnet-runtime` with the requested version
- [x] Build
  - [x] If `*.runtimeconfig.json` does not exist in the working directory, return immediately.
  - [x] If `*.runtimeconfig.json` exists but does not require any .NET runtimes, return immediately.
  - [x] If `*.runtimeconfig.json` exists and lists required .NET runtimes, install the ASP.NET Core dependency as [distributed by Microsoft](https://dotnet.microsoft.com/en-us/download/dotnet/6.0) into a layer that is available at `launch`.  The layer should be added to the launch-time `$PATH` and `$DOTNET_ROOT` should be set to the layer path in the launch environment.

## Motivation

 This is part of https://github.com/paketo-buildpacks/dotnet-core/issues/755.

**Comment by ForestEckhardt** [comment]
Reading the RFC it seems that the `DOTNET_ROOT` variable is no longer necessary
